### ISSUE TITLE
Crash with reference to PVP

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#49]
Object reference not set to an instance of an object.'
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.<sendPVPFight>d__84.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<sendFight>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.PFStuff.sendPVPFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.AutoPvP.sendFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
    ...
    [Call Stack Truncated]

This was in ActionLog
4/14/2020 3:08:43 AM
	Username Error : Input string was not in a correct format.

Been on the new version for hours and this is the 1st crash with PVP.
Dunno what was special about this one. 

Closed and restarted and it's just saying (Not Responding) in the window title bar
ErrorLog has
4/14/2020 3:25:11 AM
	Error ConnectionError A task was canceled.
4/14/2020 3:29:15 AM
	Error ConnectionError A task was canceled.

Changed Settings.json to not look for someone higher, but to attack someone lower and it worked.
Now, if it works on the next battle....¯\_(ツ)_/¯

**Comment by MatthieuBonne** [comment]
I think it's related to my user being renamed "null" for who knows why. Is it still happening ?

**Comment by MatthieuBonne** [comment]
Oh, it's a bug, I found it ! Sorry. Please download new exe.

**Comment by Vitae666** [comment]
Funny thing. The battle after I posted went fine. I went to sleep. Woke up (DAMN!) And the PVP timer was -6hrs 
But downloading the new one now.

**Comment by Vitae666** [comment]
OOHHH!!!! I knew I forgot something I wanted to ask for!
Sooooo......PVP timer -6hrs means at least 6 attacks possible. Only way to do those 6 is to uncheck/recheck "Enable Auto-PVP" 6 times.
Can CQA know how many attacks you have stored and just do them all?
Have had CQA crash on me and of course, sleeping or working, it builds up the extra attacks. Would help :)
Just a thought :)

**Comment by Vitae666** [comment]
Ok. Maybe coincidental, but I was doing the Un/Rechecking for the PVP's and this was in my ActionLog

4/14/2020 1:11:54 PM
	Object reference not set to an instance of an object.
4/14/2020 1:12:14 PM
	Object reference not set to an instance of an object.
4/14/2020 1:12:31 PM
	Object reference not set to an instance of an object.
4/14/2020 1:31:24 PM
	Object reference not set to an instance of an object.
4/14/2020 1:32:15 PM
	Object reference not set to an instance of an object.

Unsure if it's exactly those since there's no log of the PVP battles (cough) to match it to. But the 1:12 to 1:31 break was about the time I forgot what I was doing and went and did other stuff around the house.
But all the PVP's went off without a hitch, so, dunno.

**Comment by MatthieuBonne** [comment]
I've slightly improved PvP autofight in next commit, please tell me if it helps.

**Comment by Vitae666** [comment]
Not sure if the improvement is the requested use all spare fights or not.
I closed down CQA for about 6hrs by mistake. Realized it, and when I opened it up, I was a minute from PVP, but it did one. Then after the roll over, it did another and I figured "nope" BUT then it did another one like 30 seconds later.
Then no more. Still have some spares, so guess not. :)

Plus side, since I had to do the Un/Rechecking, those Object errors didn't show up in ActionLog.

**Comment by MatthieuBonne** [comment]
Ok then, another improvement in next commit.

**Comment by Vitae666** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.<sendPVPFight>d__85.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<sendFight>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.PFStuff.sendPVPFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
	CQFollowerAutoclaimer.AutoPvP.sendFight(int)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
	CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
    ...
    [Call Stack Truncated]
