### ISSUE TITLE
Crash with reference to Level

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#52]
TL;DNTR (To Long; Don't Need To Read...yeah, I made that up, so what? ;-) )
My test build with changing line 67 of Constants.cs from "B-day" to "B-Day" seems to have worked.
No crash when I changed to B-Day under PG and CC. No idea if I got lucky like I did with the Chests initially working then not, tho.

_**Note: All the below is SOLELY happening with B-Day under PG and CC**_ 

For Prana Gems I had Bavah selected. I opened a Hero chest with Bavah and I just went to the Level Tab and chose B-Day because I wanted to reload Bavah to have the right level displayed, and got this

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.


************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CQFollowerAutoclaimer.PFStuff.getHeroLevel(String heroName)
   at CQFollowerAutoclaimer.AutoLevel.updateHeroLevels()
   at CQFollowerAutoclaimer.Form1.PranaHeroCombo_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CQ Auto-follower-claimer-inator
    Assembly Version: 4.5.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Users/jweiss/Desktop/MISC/CosmosQuest/CQ%20Auto-follower-claimer-inator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Users/jweiss/Desktop/MISC/CosmosQuest/CQ%20Auto-follower-claimer-inator.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
LinqToTwitter.netstandard
    Assembly Version: 5.0.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Users/jweiss/Desktop/MISC/CosmosQuest/CQ%20Auto-follower-claimer-inator.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**THEN CQA itself crashed with**

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.getHeroLevel(String heroName)
   at CQFollowerAutoclaimer.AutoLevel.updateHeroLevels()
   at CQFollowerAutoclaimer.Form1.<getData>d__36.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CQFollowerAutoclaimer.AutoLevel.<levelTimer_Elapsed>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.PFStuff.getHeroLevel(string)
	CQFollowerAutoclaimer.AutoLevel.updateHeroLevels()
	CQFollowerAutoclaimer.Form1.getData()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	CQFollowerAutoclaimer.AutoLevel.levelTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
	System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object)
	System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object, bool)
    ...
    [Call Stack Truncated]

```

Nothing outputted to any log.

Also, I did this 3 more times, just for the hell of it. Both types of crash msgs every time.
I went thru every single other hero and no issue. As soon as I hit B-Day, BOOM!
I thought it might be something with the - but Kumu-San is fine.
It's also crashing when I hit B-Day on CC under Levels.

**EDIT:** For curiosities sake, I changed Bavah to B-Day in the Setting.json and it immediately crashed on load-up.

**EDIT 2:** Likely it has nothing to do with it, but lines of Constants.cs says "B-day" and "B-Day" while Kuma-San is "Kumu-San".
I know capitalization matters because when I was doing the test for the Hero and Normal chests, I changed then from hero/normal to Hero/Normal so that it looked better and it crashed. Soooo....maybe?

**Comment by MatthieuBonne** [comment]
You're entirely right, it's about the capital D ! Well done. It'll be fixed in next commit (later today).
