### ISSUE TITLE
Crash. Dunno when. Was at work for 9hrs

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#53]
Nothing in a log. This was from the compiler's debugger
Tho, I'm guessing it's not much more than a lost connection to CQ?

```
Inner Exception 1:
WebException: Unable to connect to the remote server
This exception was originally thrown at this call stack:
	System.Net.Sockets.Socket.InternalEndConnect(System.IAsyncResult)
	System.Net.Sockets.Socket.EndConnect(System.IAsyncResult)
	System.Net.ServicePoint.ConnectSocketInternal(bool, System.Net.Sockets.Socket, System.Net.Sockets.Socket, ref System.Net.Sockets.Socket, ref System.Net.IPAddress, System.Net.ServicePoint.ConnectSocketState, System.IAsyncResult, out System.Exception)


Inner Exception 2:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 91.121.51.196:80

System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.PFStuff.<sendBuyLTO>d__97.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AuctionHouse.<getAuctionInterval>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoWB.<getWebsiteData>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	System.Net.Sockets.Socket.InternalEndConnect(System.IAsyncResult)
	System.Net.Sockets.Socket.EndConnect(System.IAsyncResult)
	System.Net.ServicePoint.ConnectSocketInternal(bool, System.Net.Sockets.Socket, System.Net.Sockets.Socket, ref System.Net.Sockets.Socket, ref System.Net.IPAddress, System.Net.ServicePoint.ConnectSocketState, System.IAsyncResult, out System.Exception)
```

EDIT: WELL, I got 8 available PVP attacks...soooo....at least 8hrs ago :)

**Comment by MatthieuBonne** [comment]
I'm adding debug lines to actionlog to understand what's wrong, when bug happens again please copy those lines here.

**Comment by Vitae666** [comment]
Haven't had it again.
Took a look and the only place that TaskAwaiter`1 appears is in the LinqToTwitter.AspNet.dll and LinqToTwitter.netstandard.dll files. So, it mighta been a blip with Twitter.
