### ISSUE TITLE
Solved: Tried to make a build of the latest and....

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#55]
Ok, so I tried to make a build with the current commit because I changed some code of yours to select my top 60 heroes and when I opened the CQMacroCreator.sln I got the below.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Ce projet fait référence à des packages NuGet qui sont manquants sur cet ordinateur. Utilisez l'option de restauration des packages NuGet pour les télécharger. Pour plus d'informations, consultez http://go.microsoft.com/fwlink/?LinkID=322105. Le fichier manquant est : ..\packages\Costura.Fody.4.1.0\build\Costura.Fody.props.	CQMacroCreator	C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQMacroCreator-master\CQMacroCreator\CQMacroCreator.csproj	166	

When I tried the build, I got the same above, and all this extra.
Warning		The referenced component 'System.Core' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Drawing' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Windows.Forms' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Xml' could not be found.	CQMacroCreator			
Warning		The referenced component 'WindowsBase' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Data' could not be found.	CQMacroCreator			
Warning		The referenced component 'Costura' could not be found.	CQMacroCreator			
Warning		The referenced component 'Newtonsoft.Json' could not be found.	CQMacroCreator			
Warning		The referenced component 'Microsoft.CSharp' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Deployment' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Net.Http' could not be found.	CQMacroCreator			
Warning		The referenced component 'System' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Xml.Linq' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Data.DataSetExtensions' could not be found.	CQMacroCreator			
Warning		The referenced component 'System.Windows' could not be found.	CQMacroCreator

**Comment by Vitae666** [comment]
Followed the directions in the link. It downloaded/installed some Fody thing (Higher # than the one listed above) and it worked after a restart.
https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting

**Comment by MatthieuBonne** [comment]
Sorry i forgot to include packages directory in MC ; it's fixed now.

**Comment by Vitae666** [comment]
Oddly, tried to build with the new version but got

```
Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'file:///C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQMacroCreator-master\packages\Fody.6.1.1\netclassictask\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Type:
System.IO.FileLoadException
StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at IsolatedAssemblyLoadContext.CreateInstanceFromAndUnwrap() in C:\projects\fody\FodyCommon\IsolatedAssemblyLoadContext.cs:line 21
   at Processor.ExecuteInOwnAssemblyLoadContext() in C:\projects\fody\Fody\Processor.cs:line 125
   at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 119
   at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 47
Source:
mscorlib
TargetSite:
System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Type:
System.NotSupportedException
StackTrace:	

```

I went to the link at the bottom. Didn't understand anything there. But at the top it said if the error was in Visual Studio, to go tho another link....didn't understand that either.
Talking about unblocking, which is what I always have to do with Form1.resx but it's like saying that I need to do that with every file now? I'm unsure and if so, that's a hell of a task :(

**_EDIT:_**
Never mind. Had to Unblock FodyIsolated.dll and it worked.
I'll be damned if I understand why when I download the zip and extract it, it does all this weird "Oh noes! Dis from da web!"
![image](https://user-images.githubusercontent.com/9310914/80315965-0c22b980-87c9-11ea-9381-21e3a211ab1d.png)

**Comment by MatthieuBonne** [comment]
Strange indeed ! If anyone has a clue why it happens... (I'm no VS guru ^^)
