### ISSUE TITLE
No clue. Came home to it. System.NullReferenceException

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#56]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs)
	System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_1(object)
	System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object)
	System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object, bool)
	System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, object, bool)
	System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
	System.Threading.ThreadPoolWorkQueue.Dispatch()
	System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by MatthieuBonne** [comment]
I see no mention of CQA code (like a method name), really hard to guess where it comes from... :\

**Comment by Vitae666** [comment]
Dunno. I just report 'em :)

**Comment by Vitae666** [comment]
Haven't had it happen again. Mighta just been a glitch in the Matrix. Or just me....who knows :)
