### ISSUE TITLE
"External Code" causing a crash?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#57]
Starting with the latest commit, I have had crashes, but there is ZERO info about it. I don't know if it's related to the new PVP code. Or if it's something else. 
It's not DQ or event related because DQ's have been done, and it's in the middle of whatever event is going on and those are usually done quickly.
It says it's due to "External Code" but damned if I know what that means. CQMC and Calc aren't running when it's been happening.

![image](https://user-images.githubusercontent.com/9310914/80826535-69937d80-8bb0-11ea-9456-0f7db881b410.png)

**Comment by MatthieuBonne** [comment]
Are you slowly raising debug difficulty or what ? xD
Honestly I'm clueless. New exe coming soon, we'll see if bug happens again !

**Comment by Vitae666** [comment]
I'm leveling up!!
Yeah, it's weird and it happens a lot. I mean when I come back from work, or wake up, it's crashed.
Maybe it misses me 😂

**Comment by Vitae666** [comment]
ok, so I FINALLY was home and at my desk when it happened, so I know exactly where it was in time
Here's the weird thing, there's actual info in there. the External Code is just an extra bit. Don't understand why.

Just that one bit in ErrorLog then the rest was hidden...above?...the External Code.
```
5/7/2020 1:29:52 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 72167D0BC46F36CE


System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.<sendPVPFight>d__86.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<sendFight>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```

**Comment by MatthieuBonne** [comment]
I may have an idea, try next commit please.

**Comment by Vitae666** [comment]
```
5/16/2020 4:11:20 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 79DBC224BFC200F6
5/16/2020 4:11:26 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"Can't fight"} vs player 7CD269014A838A19


System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CQ Auto-follower-claimer-inator
  StackTrace:
   at CQFollowerAutoclaimer.PFStuff.<sendPVPFight>d__87.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<sendFight>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```

:confused: 
Telling ya. Never got this during my build with
```
            this.playersBelowCount.Maximum = new decimal(new int[] {
            50,

            this.playersAboveCount.Maximum = new decimal(new int[] {
            50,

```
I mean, the "Can't fight" errors, yeah. But not these crashes.

**Comment by Vitae666** [comment]
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at CQFollowerAutoclaimer.AutoPvP.<sendFight>d__7.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\AutoPvP.cs:line 87
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.TaskQueue.<queueTimer_Elapsed>d__3.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\TaskQueue.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
    CQFollowerAutoclaimer.AutoPvP.sendFight(int) in AutoPvP.cs
    [External Code]
    CQFollowerAutoclaimer.TaskQueue.queueTimer_Elapsed(object, System.Timers.ElapsedEventArgs) in TaskQueue.cs
    [External Code]

**Comment by Vitae666** [comment]
CQA crash. New one. This time apparently with WB?

> System.IO.IOException
>   HResult=0x80131620
>   Message=Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
>   Source=System
>   StackTrace:
>    at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.IO.StreamReader.ReadBuffer()
>    at System.IO.StreamReader.ReadToEnd()
>    at CQFollowerAutoclaimer.PFStuff.<getWBData>d__83.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\PFStuff.cs:line 805
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at CQFollowerAutoclaimer.AutoWB.<WBTimer_Elapsed>d__7.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\AutoWB.cs:line 87
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> SocketException: An existing connection was forcibly closed by the remote host
>

**Comment by MatthieuBonne** [comment]
Adding failsafes and debug info for these bugs.

**Comment by MatthieuBonne** [comment]
Please tell me if 4.7.4 improves the situation.

**Comment by Vitae666** [comment]
One of those "I keep forgetting to click Debug when it crashes" things.
Closing for now.
