### ISSUE TITLE
PVP crash

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#78]
```
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.PFStuff.<sendT2Register>d__105.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\PFStuff.cs:line 1185
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<TourTimer_Elapsed>d__9.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\AutoPvP.cs:line 153
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: Unable to connect to the remote server

Inner Exception 2:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 91.121.51.196:80

```

**Comment by Vitae666** [comment]
Only posting these because in all this time, I've never seen multiple Exceptions pop up.
And I'm pretty sure this isn't an internet on my side thing. It happened as I was scrolling, easily, thru Facebook. Reason I say "easily" is just because there was no stuttering in the scroll like a quick bad connection would show :)
**Also, quick note:** The other day, my PVP bar was full. I hadn't attacked in hours. Did a manual one and it kickstarted it. Still don't think that that or a few of my other issues are an internet thing on my side. If they were they would fix themselves during a Refresh or 2, not last for hours with 30 or so Refreshes every hour.

```
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.PFStuff.<sendT2Register>d__105.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\PFStuff.cs:line 1185
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<TourTimer_Elapsed>d__9.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\AutoPvP.cs:line 153
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The underlying connection was closed: An unexpected error occurred on a receive.

Inner Exception 2:
IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.

Inner Exception 3:
SocketException: An established connection was aborted by the software in your host machine

```

**Comment by MatthieuBonne** [comment]
Wasn't this during kong maintenance ?

**Comment by Vitae666** [comment]
Not sure, and I'm almost 100% certain that I'd visited the game itself in between those crashes.
At least based on my post dates: Sep 14, 2020, 1:43 PM EDT - Sep 15, 2020, 9:43 AM EDT
But I'm sure I would have visited after the 1st one, since it's around the time I wake up for work. A crash always sends me to the game to see what's up (Panic attack that the game is gone LOL)

Or are you asking about the full PVP bar? Which either way would have been hours.

**Comment by MatthieuBonne** [comment]
Please update :)
