### ISSUE TITLE
sendT1Register crash, I guess?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#79]
```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.PFStuff.<sendT1Register>d__104.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\PFStuff.cs:line 1146
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoPvP.<TourTimer_Elapsed>d__9.MoveNext() in C:\Users\jweiss\Desktop\MISC\CosmosQuest\CQAutomater-master\CQFollowerAutoclaimer\AutoPvP.cs:line 147
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
    CQFollowerAutoclaimer.PFStuff.sendT1Register() in PFStuff.cs
    [External Code]
    CQFollowerAutoclaimer.AutoPvP.TourTimer_Elapsed(object, System.Timers.ElapsedEventArgs) in AutoPvP.cs
    [External Code]
```

**Comment by Vitae666** [comment]
Ok, didn't know there was an update until now. 
MAYBE it was during that time. The last time something was logged was around 8:30ish PM EST. And Simoris posted at 7:33 PM the patch notes.
