### ISSUE TITLE
Crashes on latest version

### ISSUE THREAD

**Issue by Cerobug** [MatthieuBonne/CQAutomater#81]
Getting crashes on the latest version quite often. Here's my errorlog.

10/26/2020 11:32:26 PM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
10/27/2020 3:42:30 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
10/27/2020 3:42:32 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
10/27/2020 5:47:40 AM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
10/27/2020 5:47:42 AM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)

**Comment by Vitae666** [comment]
Get that as well kinda often even before the builds this month. Been
ignoring it cause I know my internet is crap so I figure that's part of it.
(No Matt, nothing to do with the other bugs I've mentioned 😝)
But I will say that as of the past 3-4 weeks or so, as soon as I log into
the game I am getting a "the server is overloaded" pop up box. So it MIGHT
be related to that.

**Comment by MatthieuBonne** [comment]
It's a network issue, perhaps linked to playfab overload. But that shouldn't crash CQA...

**Comment by Cerobug** [comment]
More Issues in error log and crashing now that tournaments are back

10/29/2020 2:00:34 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:08:28 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:14:47 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:20:04 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:25:21 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:29:36 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:33:19 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:33:54 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:40:13 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:45:00 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:49:15 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:50:52 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 2:54:36 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 3:04:03 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 3:05:09 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]
10/29/2020 3:06:46 AM
	Error sendT1Register for user 32273 [-165,-25,-91,121,-49,114,-58,-180,-147,121,-119,116,97,-22,-11,-60,-52,-213,-55,-81,-141,-199,-4,-148,-20,-218,-172,-98,-150,-182]

**Comment by Vitae666** [comment]
I don't think I've joined a T1 yet either

> More Issues in error log and crashing now that tournaments are back
>

**Comment by Vitae666** [comment]
I don't think I've joined a T1 yet either
![image](https://user-images.githubusercontent.com/9310914/97616049-6a3b8e00-19f2-11eb-918d-52128c6c196b.png)

EDIT: Well, I checked and unchecked "Enable Auto-T1" and I instantly joined. *shrug*

EDIT 2: Well, forget that...haven't joined the current one yet. Did the check/uncheck again, and it hasn't joined.
BTW, is it just me or is paying 250UM for a LOW chance of getting 80PG ridiculous when it's a 1:1 ratio in the Hero Manager Screen?

**Comment by Cerobug** [comment]
I am still getting random crashes quite often. Here's the last few lines of my error log. It still won't join T1 also.

	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/2/2020 4:42:54 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/3/2020 1:20:57 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player 6234656DD7E9C2E2
11/3/2020 1:20:58 PM
	Error PvP Fight impossible vs index 6234656DD7E9C2E2 (nearbyPlayersIDs = ["FB6C516D7CE381CA","CE94EC159393ACFE","1FBF1B36B19FBC7E","23250BBF5E270F80","6234656DD7E9C2E2","96283A61E163F075","58111489A0BD7F4B","C48E993825EA835","D22AC55B09AAD101","F648F0951BFFD9A6"])
11/3/2020 1:21:02 PM
	Error PvP Catched error Object reference not set to an instance of an object. vs index 4 (96283A61E163F075) (nearbyPlayersIDs = ["FB6C516D7CE381CA","CE94EC159393ACFE","1FBF1B36B19FBC7E","23250BBF5E270F80","96283A61E163F075","58111489A0BD7F4B","C48E993825EA835","D22AC55B09AAD101","F648F0951BFFD9A6"])

**Comment by Cerobug** [comment]
It has been crashing again after a few days of working fine. Here's the log info from yesterday.

11/9/2020 3:18:18 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/9/2020 3:18:20 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/9/2020 11:50:27 AM
	Error sendT2Register for user 32273 [-12,-214,-7,-69,-213,-177,-22,-148,-186,-57,178,-135,-184,-73,-141,-1,-1,-1,-204,-55,-154,-129,-45,-34,-11,-31,-13,-67,-228,-71]
11/9/2020 1:12:17 PM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/9/2020 1:12:19 PM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/9/2020 1:20:54 PM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/9/2020 1:20:56 PM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/9/2020 2:20:19 PM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/9/2020 2:20:21 PM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/9/2020 5:27:46 PM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/9/2020 5:27:48 PM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/9/2020 10:04:31 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player 45D7B63B493BF5F7
11/9/2020 10:04:32 PM
	Error PvP Fight impossible vs index 45D7B63B493BF5F7 (nearbyPlayersIDs = ["E49A7FAE291C7DF5","45D7B63B493BF5F7","96283A61E163F075","8295E0BFE3CCECF7","D2D72A208E41283A"])
11/9/2020 10:04:35 PM
	Error PvP Catched error Object reference not set to an instance of an object. vs index 1 (96283A61E163F075) (nearbyPlayersIDs = ["E49A7FAE291C7DF5","96283A61E163F075","8295E0BFE3CCECF7","D2D72A208E41283A"])
11/10/2020 2:24:18 AM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/10/2020 2:24:20 AM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/10/2020 3:05:22 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/10/2020 3:05:24 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)

**Comment by MatthieuBonne** [comment]
I've added more detailed logging to see if it's linked to pvp : please update :)

**Comment by Cerobug** [comment]
More logs from more crashing over last few days

11/12/2020 11:45:28 PM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/13/2020 2:09:33 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/13/2020 2:09:35 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/13/2020 3:18:11 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/13/2020 3:18:13 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/13/2020 11:58:58 AM
	Error getWebsiteData  http failed, retrying --- The remote name could not be resolved: 'cosmosquest.net'
11/13/2020 11:59:00 AM
	Error getWebsiteData  The remote name could not be resolved: 'cosmosquest.net' ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/13/2020 4:29:40 PM
	Error getWebsiteData  http failed, retrying --- The request was aborted: Could not create SSL/TLS secure channel.
11/13/2020 4:29:42 PM
	Error getWebsiteData  The request was aborted: Could not create SSL/TLS secure channel. ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/13/2020 10:35:04 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"You already attacked this player"} vs player 48C7551ADAADCA4F
11/13/2020 10:35:05 PM
	Error PvP Fight impossible vs index 48C7551ADAADCA4F (nearbyPlayersIDs = ["BBB334090299BD68","FBE1A9BCEE8C3ECA","96283A61E163F075","48C7551ADAADCA4F","BD72880E8F235342"])
11/13/2020 10:35:08 PM
	Error PvP Catched error Index was outside the bounds of the array.
11/14/2020 7:34:34 AM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/14/2020 7:34:36 AM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
11/14/2020 10:25:19 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"You already attacked this player"} vs player BBB334090299BD68
11/14/2020 10:25:20 PM
	Error PvP Fight impossible vs index BBB334090299BD68 (nearbyPlayersIDs = ["BBB334090299BD68","74D55DDC4B41C073","96283A61E163F075","483A77642A35EE9A","E243F2C990E528A6"])
11/15/2020 3:45:56 AM
	Error flash error before sendFlashRegister An error occurred while sending the request. --- {"id":3871,"hero":[0,0,0,69,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,0,42,0,0,0,0,0,0,0,0,7,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"followers":423859,"joined":false,"players":1,"promo":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

**Comment by Vitae666** [comment]
Latest version came out 7hrs before your post. Did you update?

**Comment by Cerobug** [comment]
More Crashing

11/15/2020 4:28:51 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player 6CF2CF85011B3607
11/15/2020 4:28:52 PM
	Error PvP Fight impossible vs index 6CF2CF85011B3607 (nearbyPlayersIDs = ["8884296C0675D304","2C3DF6347CB1C075","96283A61E163F075","6CF2CF85011B3607","B9988BD280B9FFC3"])
11/15/2020 4:28:55 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player 8884296C0675D304
11/15/2020 4:28:56 PM
	Error PvP Fight impossible vs index 8884296C0675D304 (nearbyPlayersIDs = ["8884296C0675D304","2C3DF6347CB1C075","96283A61E163F075","B9988BD280B9FFC3"])
11/15/2020 4:28:59 PM
	Error PvP Catched error Index was outside the bounds of the array.
11/15/2020 4:29:03 PM
	Error PvP Catched error Index was outside the bounds of the array.
11/15/2020 4:29:07 PM
	Error Cloud Script Error: PvP Fight {"ok":false,"err":"No charges left"} vs player 2C3DF6347CB1C075
11/15/2020 4:29:08 PM
	Error PvP Fight impossible vs index 2C3DF6347CB1C075 (nearbyPlayersIDs = ["2C3DF6347CB1C075","96283A61E163F075","B9988BD280B9FFC3"])
11/15/2020 4:29:11 PM
	Error PvP Catched error Object reference not set to an instance of an object.
11/15/2020 4:29:28 PM
	Error updateFlashHistory  One or more errors occurred. ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CQFollowerAutoclaimer.PFStuff.updateFlashHistory(JToken json)
11/15/2020 6:07:25 PM
	Error getWebsiteData  http failed, retrying --- Unable to connect to the remote server
11/15/2020 6:07:27 PM
	Error getWebsiteData  Unable to connect to the remote server ---    at System.Net.HttpWebRequest.GetResponse()
   at CQFollowerAutoclaimer.PFStuff.getWebsiteData(String id)
